#!/usr/bin/env python

import subprocess


def get_vrams():
    proc = subprocess.Popen(['vram'], stdout=subprocess.PIPE)
    out, err = proc.communicate()

    if not err:
        ret = out[:-1] if out[-1] == '\n' else out
        return ret.split(' ')
    return ""


def get_from_atiflash():
    proc = subprocess.Popen(['sudo', 'atiflash', '-i'], stdout=subprocess.PIPE)
    out, err = proc.communicate()

    lst = out.splitlines()
    ret = []
    for s in lst[3:]:
        row = [l for l in s.split(' ') if l]
        ret.append({
            'ssid': row[3],
            'model': row[4],
            'flash-type': row[5],
            'rom-size': row[6],
            'bios-version': row[8],
        })
    return ret


def get_gpu_list():
    pass


def main():
    vrams = get_vrams()
    cards = get_from_atiflash()
    for card, vram in zip(cards, vrams):
        card['vram-size'] = vram
        print card
    print "Done"


if __name__ == "__main__":
    main()
